#!/usr/bin/env bash

run_nvim() {
	if [ $# -eq 0 ]; then
		nvim .
	else
		nvim $1
	fi
}

# git
alias gs='git status'
alias gm='git merge --no-ff'
alias gmf='git merge --ff-only'
alias glist='for ref in $(git for-each-ref --sort=-committerdate --format="%(refname)" refs/heads/ refs/remotes ); do git log -n1 $ref --pretty=format:"%Cgreen%cr%Creset %C(yellow)%d%Creset %C(bold blue)<%an>%Creset%n" | cat ; done | awk '"'! a["'$0'"]++'"
alias ga='git commit --amend --no-edit;'
alias gap='git commit --amend --no-edit; git push -f origin HEAD --no-verify'
alias gp='git push origin HEAD && git push --tags'
alias gcontrib='git shortlog -s -n'

# ls
alias l="ls -lF ${colorflag}"
alias la='ls -la'
alias dun='list-space' # easier to type

# cd
alias cdh='cd ~/'
alias cddrop='cd ~/Dropbox'
alias cddev='cd ~/dev'
alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'

alias cd..='cd ..'
alias cd...='cd ../..'
alias cd....='cd ../../..'

alias d="cd ~/Dropbox"
alias dl="cd ~/Downloads"
alias c='c'
alias h='cd ~/'

# docker
alias dm='docker-machine'
alias up='docker-compose up'

# Other util
alias his='history | grep $1'
alias grep='grep --color=auto'
alias dockerips='docker inspect -f "{{.Name}} - {{.NetworkSettings.IPAddress }}" $(docker ps -aq)'
alias journal='cwd=$(pwd) && cd ~/Dropbox/Private/journal && mkdir -p $(date "+%Y") && cd $(date "+%Y") && mkdir -p $(date "+%m") && $(date "+%m") && nvim $(date "+%d-%m-%Y").md && cd $cwd'
alias j=journal
alias n=run_nvim
alias path='echo -e ${PATH//:/\\n}'
alias e=exit
alias mux='tmuxinator'
alias kk='kill %1'

# IP addresses
alias ip="dig +short myip.opendns.com @resolver1.opendns.com"
