#!/usr/bin/env bash


# `tre` is a shorthand for `tree` with hidden files and color enabled, ignoring
# the `.git` directory, listing directories first. The output gets piped into
# `less` with options to preserve color and line numbers, unless the output is
# small enough for one screen.
tre() {
	tree -aC -I '.git|node_modules|bower_components' --dirsfirst "$@" | less -FRNX
}

addToPath() {
	if [[ "$PATH" != *"$1"* ]]; then
		export PATH=$PATH:$1
	fi
}


# Create a new directory and enter it
mkd() {
	mkdir -p "$@" && cd "$_"
}

nvims() {
	config=$(printf "%s\n" $(ls ~/.config | grep nvim) | fzf --prompt=" Neovim Config  " --height=50% --layout=reverse --border --exit-0)
	if [[ -z $config ]]; then
		echo "Nothing selected"
		return 0
	elif [[ $config == "nvim" ]]; then
		config=""
	fi
	NVIM_APPNAME=$config nvim $@
}
