#!/usr/bin/env bash

export PATH=$PATH:$HOME/bin
export PATH=$PATH:/usr/bin

# path for go programming language
export PATH=$PATH:/usr/local/go/bin
export PATH="$PATH:$GOPATH/bin"

# add RVM to PATH for scripting
export PATH="$PATH:$HOME/.rvm/bin"

export PATH=$PATH:$HOME/dotfiles/bin

export PATH="$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$PATH"
