#!/usr/bin/env bash

addToPath /usr/local/go/bin
addToPath /usr/bin
addToPath $HOME/bin
addToPath $GOPATH/bin
addToPath $HOME/.rvm/bin
addToPath $HOME/dotfiles/bin
addToPath $HOME/.yarn/bin
addToPath $HOME/.config/yarn/global/node_modules/.bin
addToPath $HOME/miniconda3/bin
