ZSH=$HOME/.oh-my-zsh

# Liquid prompt
# https://github.com/nojhan/liquidprompt
# Only load Liquid Prompt in interactive shells, not from a script or from scp
#[[ $- = *i* ]] && source ~/code/liquidprompt/liquidprompt

ZSH_THEME="sonicradish"

# Comment this out to disable bi-weekly auto-update checks
#DISABLE_AUTO_UPDATE="true"

# Uncomment to change how many often would you like to wait before auto-updates occur? (in days)
export UPDATE_ZSH_DAYS=30

# Uncomment following line if you want red dots to be displayed while waiting for completion
COMPLETION_WAITING_DOTS="true"

plugins=(
    git
    fzf
    last-working-dir
)

export SHELL_DIR=~/dotfiles/shell

LOCAL_OVERRIDES=$SHELL_DIR/local-overrides
if test -f "$LOCAL_OVERRIDES"; then
  source $LOCAL_OVERRIDES
fi

if [[ -d /opt/homebrew/opt/fzf ]]; then
  export FZF_BASE=/opt/homebrew/opt/fzf
elif [[ -d /usr/local/opt/fzf ]]; then
  export FZF_BASE=/usr/local/opt/fzf
elif [[ -d /usr/share/doc/fzf ]]; then
  export FZF_BASE=/usr/share/doc/fzf
fi
source $ZSH/oh-my-zsh.sh

source $SHELL_DIR/config

~/dotfiles/bin/check-cookies-being-cleaned.py

