ZSH=$HOME/.oh-my-zsh

# Liquid prompt
# https://github.com/nojhan/liquidprompt
# Only load Liquid Prompt in interactive shells, not from a script or from scp
#[[ $- = *i* ]] && source ~/code/liquidprompt/liquidprompt

ZSH_THEME="sonicradish"

# Comment this out to disable bi-weekly auto-update checks
#DISABLE_AUTO_UPDATE="true"

# Uncomment to change how many often would you like to wait before auto-updates occur? (in days)
export UPDATE_ZSH_DAYS=30

# Uncomment following line if you want red dots to be displayed while waiting for completion
COMPLETION_WAITING_DOTS="true"

plugins=(
    git
    last-working-dir
)

source $ZSH/oh-my-zsh.sh

export SHELL_DIR=~/dotfiles/shell
source $SHELL_DIR/config

