#!/usr/bin/env bash

awslogin() { saml2aws login && eval $(saml2aws script) }

backup() {
  echo backing up linux...

  tar -cvpzf ~/backup/code.tar.gz \
  --exclude=.git \
  --exclude=node_modules \
  --exclude=userdata \
  ~/code

  tar -cvpzf ~/backup/dconf.tar.gz \
  ~/.config/dconf
}

cleancache() {
  find ~/.cache/ -type f -atime +365 -delete
}
