#!/usr/bin/env bash

awslogin() { saml2aws login && eval $(saml2aws script) }

backup() {
  echo backing up linux...

  tar -cpzf ~/backup/code.tar.gz \
  --exclude-ignore=.tarignore \
  --exclude-ignore=.gitignore \
  --exclude=.git \
  --exclude=node_modules \
  --exclude=userdata \
  --exclude=coe-project \
  --exclude=data \
  --exclude=data3 \
  --exclude=ammo.js \
  ~/code

  tar -cpzf ~/backup/dconf.tar.gz \
  ~/.config/dconf
}

cleancache() {
  find ~/.cache/ -type f -atime +365 -delete
}

# `o` with no arguments opens the current directory, otherwise opens the given
# location
o() {
	if [ $# -eq 0 ]; then
		xdg-open .
	else
		xdg-open "$@"
	fi
}

addThrottle() {
	local kbs="kbps"
	echo $kbs
	echo "About to throttle to $1 $kbs"
	echo "sudo tc qdisc add dev wlp59s0 handle 1: root htb default 11"
	echo "sudo tc class add dev wlp59s0 parent 1: classid 1:1 htb rate $1$kbs"
	echo "sudo tc class add dev wlp59s0 parent 1:1 classid 1:11 htb rate $1$kbs"
	sudo tc qdisc add dev wlp59s0 handle 1: root htb default 11
	sudo tc class add dev wlp59s0 parent 1: classid 1:1 htb rate $1$kbs
	sudo tc class add dev wlp59s0 parent 1:1 classid 1:11 htb rate $1$kbs
}

removeThrottle() {
	sudo tc qdisc del dev wlp59s0 root
}

# Start an HTTP server from a directory, optionally specifying the port
server() {
	local port="${1:-8000}"
	sleep 1 && xdg-open "http://localhost:${port}/" &
	python -c $'import SimpleHTTPServer;\nmap = SimpleHTTPServer.SimpleHTTPRequestHandler.extensions_map;\nmap[""] = "text/plain";\nfor key, value in map.items():\n\tmap[key] = value + ";charset=UTF-8";\nSimpleHTTPServer.test();' "$port"
}
