#!/usr/bin/env bash

awslogin() { saml2aws login && eval $(saml2aws script) }

backup() {
  echo backing up linux...

  tar -cpzf ~/backup/code.tar.gz \
  --exclude=.git \
  --exclude=node_modules \
  --exclude=userdata \
  --exclude=coe-project \
  --exclude=data \
  --exclude=data3 \
  --exclude=ammo.js \
  ~/code

  tar -cpzf ~/backup/dconf.tar.gz \
  ~/.config/dconf
}

cleancache() {
  find ~/.cache/ -type f -atime +365 -delete
}
