#!/usr/bin/env bash

addToPath /Applications/Postgres.app/Contents/Versions/latest/bin
addToPath $HOME/.local/bin
addToPath /usr/local/opt/python/libexec/bin

# Add GHC 7.10.2 to the PATH, via https://ghcformacosx.github.io/
export GHC_DOT_APP="/Applications/ghc-7.10.2.app"
if [ -d "$GHC_DOT_APP" ]; then
  export PATH="${HOME}/.local/bin:${HOME}/.cabal/bin:${GHC_DOT_APP}/Contents/bin:${PATH}"
fi

