#!/usr/bin/env bash

addToPath /Applications/Postgres.app/Contents/Versions/latest/bin
addToPath $HOME/.local/bin
addToPath /usr/local/opt/python/libexec/bin
addToPath /opt/homebrew/bin

addToPath $HOME/code/jdk-22.0.2.jdk/Contents/Home/bin
